### ISSUE TITLE
Personal Computer Communications: SEND_DATAPC

### ISSUE THREAD

**Issue by rastreus** [gavanderhoorn/dominh#5]
@gavanderhoorn I have a follow-up question from our conversation at https://github.com/onerobotics/go-fanuc/issues/3.

In the _FANUC Robotics SYSTEM R-30iA and R-30iB Controller KAREL Reference Manual_, Table A-7. KAREL Built-In Routine Summary lists `ADD_BYNAMEPC`, `ADD_INTPC`, `ADD_REALPC`, `ADD_STRINGPC`, `SEND_DATAPC` and `SEND_EVENTPC` in a Category named "**Personal Computer Communications**".

I am interested in `SEND_DATAPC`, but I am having a difficult time finding additional information about setting it up. Do you have any experience using this KAREL built-in procedure? I guess my confusion is about `%ENVIRONMENT Group :PC`. What is being sent to "the PC" and how do you properly define "the PC"?

I looked at information about the "**%ENVIRONMENT Translator Directive**". I gather that I need to define a "PC.ev" environment file, but I am not sure what that should look like regarding syntax and what all it should contain for `SEND_DATAPC` to function properly.
> [%ENVIRONMENT Translator Directive] used by the off-line translator to specify that the binary file, path_name.ev, should be loaded. Environment files contain definitions for predefined constants, ports, types, system variables, and built-ins.

The previously mentioned reference manual explains the purpose, syntax, details and has a small example that sends event 12 to the PC with a data buffer:

```
PROGRAM TESTDATA
%ENVIRONMENT PC

CONST
  er_about = 2

VAR
  dat_buffer:   ARRAY[100] OF BYTE
  index:        INTEGER
  status:       INTEGER

BEGIN
  index = 1
  ADD_INTPC(dat_buffer, index, 55, status)
  ADD_REALPC(dat_buffer, index, 123.5, status)
  ADD_STRINGPC(dat_buffer, index, 'YES', status)

  -- send event 12 and data buffer to PC
  SEND_DATAPC(12, dat_buffer, status)
  IF status<>0 THEN
    POST_ERR(status, '', 0, er_abort)
  ENDIF
END TESTDATA
```

I am wanting to send errors to the PC. I'm unsure if the following KAREL code snippet would work or not. Do you know if using `SEND_DATAPC` in a condition handler will work?

Thanks again for any additional help or direction that you can provide.

```
PROGRAM SEND_ERR
%NOLOCKGROUP
%NOPAUSE = COMMAND + TPENABLE + ERROR
%NOBUSYLAMP
%NOABORT = ERROR + COMMAND
%COMMENT = 'SEND ERROR'
%ENVIRONMENT PC

VAR
  dat_buffer:       ARRAY[244] OF BYTE
  index:            INTEGER
  status:           INTEGER
  error_code:       INTEGER
  error_string:     STRING[40]
  cause_code:       INTEGER
  cause_string:     STRING[40]
  time_int:         INTEGER
  severity:         INTEGER
  prog_nam:         STRING[40]
  ecst,esst,ccst,csst,tist,sst,pnst: INTEGER -- status variables

BEGIN
  index = 1
  CONDITION[1]:
    WHEN ERROR[*] DO
    -- seq_num should be set to MAXINT if the most recent error is desired.
    ERR_DATA(MAXINT, error_code, error_string, cause_code, cause_string, time_int, severity, prog_nam)
    ADD_BYNAMEPC(dat_buffer, index, 'SEND_ERR', 'ERROR_CODE', ecst)
    ADD_BYNAMEPC(dat_buffer, index, 'SEND_ERR', 'ERROR_STRING', esst)
    ADD_BYNAMEPC(dat_buffer, index, 'SEND_ERR', 'CAUSE_CODE', ccst)
    ADD_BYNAMEPC(dat_buffer, index, 'SEND_ERR', 'CAUSE_STRING', csst)
    ADD_BYNAMEPC(dat_buffer, index, 'SEND_ERR', 'TIME_INT', tist)
    ADD_BYNAMEPC(dat_buffer, index, 'SEND_ERR', 'SEVERITY', sst)
    ADD_BYNAMEPC(dat_buffer, index, 'SEND_ERR', 'PROG_NAM', pnst)
    IF (ecst=0) AND (esst=0) AND (ccst=0) AND (csst=0) AND (tist=0) AND (sst=0) AND (pnst=0) THEN
      SEND_DATAPC(0, dat_buffer, status)
    ENDIF
    index = 1
  ENDCONDITION
  ENABLE CONDITION[1]
END SEND_ERR
```

**Comment by gavanderhoorn** [comment]
Apologies for my delayed reply.

It's been too long since I've used/looked at any of this, so I'm afraid I wouldn't be able to help you.

If I remember correctly, you were looking to push information about errors to a remote host.

Is there any reason you cannot "simply" open a socket and use the regular socket functionality of Karel?

On newer controllers you can even open UDP sockets, which could make this even easier (ie: no requirement for the remote host to be online).

**Comment by gavanderhoorn** [comment]
As this seems off-topic for this tracker, I'm going to close it.

Feel free to keep commenting on it of course.
